### PR TITLE
create manvfat.md

### PR DESCRIPTION
**Pull request by mikechristopher**
Need anymore info feel free to give me a shout 👍

### CODE REVIEW

**Comment by felicianotech** [comment]
Hey @mikechristopher, thank you.

Would you be able to run the update script as specified in the README so that talk.manvfat.com's data can be pulled in?

**Comment by mikechristopher** [comment]
Hi @felicianotech how would I do that as have never used Hugo before?

**Comment by felicianotech** [comment]
It's at the bottom of the readme:

> ./bin/pull-updates src/content/communities/manvfat.md

So in this case, you'd run `./bin/pull-updates src/content/communities/the-name.md`

which will update your new file with data and download the favicon. Then, `git add` the new/changed files and commit that.

**Comment by mikechristopher** [comment]
Apologies a new one on me as created this straight on the web (still learning).  However I have downloaded git & hugo (using windows), have created a clone and using hugo created the new file as per the instructions etc.

When trying to run the above command (in cmd or git bash) once its been saved etc it says no such file or directory, I did notice there was no pull-updates file in the bin directory?  There is a pull-data but that just comes up cannot execute binary file when trying to run it.   Do I need to install anything else to run it?  

Thanks!

**Comment by felicianotech** [comment]
Ah okay. I'll update this for you. The script will only run in a Unix environment (Linux or macOS), not on Windows.

**Comment by felicianotech** [comment]
Thank you for submitting!

**Pull request merged**
